pub mod url;
pub mod runtime;

// Load the snapshot generated by build.rs:
pub static DUMMY_SNAPSHOT: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/DUMMY_DENO.snapshot"));

pub static TS_VERSION: &str = "2.5.3";
