[package]
name = "core-extension-op-state-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
libdeno.workspace = true
tokio.workspace = true

[dependencies.ext]
package = "core-extension-op-state-ext"
path = "../ext"
